### ISSUE TITLE
Add CI ?

### ISSUE THREAD

**Issue by grosser** [ruby/forwardable#7]
would be nice if PRs had automated testing

**Comment by hsbt** [comment]
It's nice. I prefer to use GitHub Actions now.

**Comment by grosser** [comment]
https://github.com/ruby/forwardable/actions seems to have some setup, but the PR https://github.com/ruby/forwardable/pull/5 has no checks ... so is it just missing actions for CI ?

**Comment by znz** [comment]
Thank you for your suggestion.
it will fixed at #8
